@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Acme-Pony-Pink/project>
	deps:runtime-requirement         [ deps:on "List::MoreUtils"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "autodie"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

